### ISSUE TITLE
Unable to install it Sublime 3

### ISSUE THREAD

**Issue by DanyC97** [saltstack/sublime-text#10]
Trying to install in Sublime 3 by going to Pref -> Package Control -> Install but the saltstack doesn't show up.

Any idea?

Thx

**Comment by DanyC97** [comment]
i'm aware of #3  but it didn't do the trick for me who run it on Yosemite

**Comment by anlutro** [comment]
Works fine here: http://i.imgur.com/d1laOqE.png

Maybe try re-installing package control.

**Comment by DanyC97** [comment]
Done that and no success.
What is interesting is that if i go to Package Control -> List pkg - i can found it and the minute i click on it i get the error saying "SatlStack-related syntax highlighting and snippets" can't be found.

My ST3 build is 3083, hmm

**Comment by DanyC97** [comment]
I'll close the issue as i managed to sorted it out. Removed all the pkg, checked in the Pkg Control -> User Settings that i have nothing left in and then installed all of them back.

Thanks
