### ISSUE TITLE
yaml highlighting gets weird when using colons in jinja

### ISSUE THREAD

**Issue by Inveracity** [saltstack/sublime-text#13]
The syntax highlighting gets a little wonky when using colons inside jinja

![Image of sublime](http://i.imgur.com/XsZWCel.png)

**Comment by anlutro** [comment]
I don't have this issue - are you on the latest Sublime Text 3 version? And are you sure you're actually using the SLS syntax? It looks like just plain YAML highlighting.

**Comment by Inveracity** [comment]
I'm using Sublime Text 2 and it auto detects salt state files
![image of sublime](http://i.imgur.com/gXD9f8f.png)

Reckon I should use subblime text 3 instead then?

**Comment by Inveracity** [comment]
I uninstalled st2 and removed everything in [%APPDATA%\Sublime Text 2](https://www.sublimetext.com/docs/2/revert.html). 
Reinstalled st2, installed the package control, installed the saltstack package; no luck.
Tried sublime text 3 aswell, same result.
Any ideas?

**Comment by Inveracity** [comment]
It helps to also install Jinja2 highlighting ... 

![package control](http://i.imgur.com/Jl7Ek6e.png)

And now everything looks right for .sls files
