### ISSUE TITLE
Proper sls syntax highlighting

### ISSUE THREAD

**Issue by jmagnusson** [saltstack/sublime-text#5]
Any plans for this?

For example the comma in the following snippet makes everything on the rows below it end up yellow for me, until the next apostrophe is encountered.
```yaml
{% for cert_name, cert_data in salt['pillar.get']['secrets:certificates'].items() %}
```

**Comment by anlutro** [comment]
@eshelman https://github.com/saltstack/sublime-text/pull/6

**Comment by eshelman** [comment]
This has been merged and will be pushed into Sublime Package Control (which might take a couple days).
